### ISSUE TITLE
Panicked happened once at protocol.rs

### ISSUE THREAD

**Issue by VigneshChennai** [cloudflare/odoh-rs#3]
Sorry for an issue report with very less details as I couldn't able to reproduce the issue to generate more details. Still thought of logging an issue will be helpful.

I was trying with odoh-rs using code from https://github.com/cloudflare/odoh-client-rs/  as sample (with slight modification) and the code panicked with below error, once.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error', /Users/vignesh/.cargo/registry/src/github.com-1ecc6299db9ec823/odoh-rs-0.1.5/src/protocol.rs:447:10

I tried running it again several times with same inputs.. But it never happened again.

**Comment by tanyav2** [comment]
Hey Vignesh, I am working on making panics not happen, keep an eye out for the next release of `odoh-client-rs` which will feature `odoh-rs = 0.1.6`. Could you let me know what the modification you made to `odoh-client-rs` was?

**Comment by VigneshChennai** [comment]
Changes were nothing significant. I was just moving things around and testing stuffs. Changes I made are available here https://github.com/VigneshChennai/odoh-client-rs

**Comment by tanyav2** [comment]
I know you weren't able to replicate, but maybe try with the new version? It should be up now, `v0.1.5` of the client. Closing for now.
